SELECT  --PER.CODIGOPERSONA,
        --NVL(SP.TIPOPRESTAMO, NULL) CODTIPOPRESTAMO,
        --SP.MONEDA CODMONEDA,
        --P.ESTADO CODESTADO,
        PER.CIP,
        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(PER.NOMBRECOMPLETO, ',', ''), CHR(10),''), CHR(13),''), CHR(9),'')) NOMBRECOMPLETO,
        CASE 
            WHEN PER.TIPOPERSONA = 1 THEN
                (SELECT (SELECT S.TBLDESCRI FROM SYST900 S WHERE S.TBLCODTAB = 1 AND S.TBLCODARG = PN.TIPODOCUMENTOID)
                FROM PERSONANATURAL PN
                WHERE PN.CODIGOPERSONA = PER.CODIGOPERSONA)
            WHEN  PER.TIPOPERSONA = 2 THEN
                (SELECT S.TBLDESCRI FROM SYST900 S WHERE S.TBLCODTAB = 1 AND S.TBLCODARG = 14) --RUC
        END
            TIPODOCUMENTO,
        CASE
            WHEN PER.TIPOPERSONA = 1 THEN
                (SELECT PN.NUMERODOCUMENTOID
                FROM PERSONANATURAL PN
                WHERE PN.CODIGOPERSONA = PER.CODIGOPERSONA)
            WHEN  PER.TIPOPERSONA = 2 THEN
                TO_CHAR(PER.NUMERORUC)
            END NUMERODOCUMENTO,
        SP.PERIODOSOLICITUD || '-' || SUBSTR(LPAD(SP.NUMEROSOLICITUD, 7, '0'), 0, 2) || '-' || SUBSTR(LPAD(SP.NUMEROSOLICITUD, 7, '0'), 3, 5) SOLICITUD,
        TRIM(REPLACE(REPLACE(REPLACE(P.PAGAREANTERIOR, CHR(10),''), CHR(13),''), CHR(9),'')) PAGAREANTERIOR,
        NVL(SUBSTR((SELECT S.TBLDESCRI FROM SYST902 S WHERE S.TBLCODTAB = SP.TIPOSOLICITUD AND S.TBLCODARG = SP.TIPOPRESTAMO), 1, 35), NULL)
            TIPOPRESTAMO,
        (SELECT S.TBLDESCRI FROM SYST900 S WHERE S.TBLCODTAB = 22 AND S.TBLCODARG = SP.MONEDA)
            MONEDA,
        SP.MONTOSOLICITADO,
        (SELECT S.TBLDESCRI FROM SYST900 S WHERE S.TBLCODTAB = 25 AND S.TBLCODARG = P.ESTADO)
            ESTADO,
        TO_CHAR(TRUNC(SP.FECHASOLICITUD), 'YYYY-MM-DD') FECHASOLICITUD,
        TO_CHAR(TRUNC(P.ULTIMOCAPITAL), 'YYYY-MM-DD') FECHAULTIMO
FROM (  SOLICITUDPRESTAMO SP
        LEFT JOIN PRESTAMO P
        ON SP.PERIODOSOLICITUD || SP.NUMEROSOLICITUD = P.PERIODOSOLICITUD || P.NUMEROSOLICITUD
        )
            LEFT JOIN PERSONA PER
            ON SP.CODIGOPERSONA = PER.CODIGOPERSONA
WHERE SP.PERIODOSOLICITUD != 1
    AND SP.PERIODOSOLICITUDCONCESIONAL IS NULL
    AND SP.NUMEROSOLICITUDCONCESIONAL IS NULL
    --AND TRUNC(SP.ULTIMOCAPITAL) >= FECHAULTIMAACTUALIZACIONSICA
    AND P.ESTADO <= 2;