select * from permiso;
select * from usuario;
update permiso set nivel = 1 where id_usuario_fk = 44;
SELECT U.PASSWORDHASH, U.PASSWORDSALT, U.ID_AREA_FK, U.ID_USUARIO, U.CAMBIAR_PASSWORD, U.ACCESO_PERMITIDO, U.CERRAR_SESION, P.BUSQUEDA, P.BUSQUEDA_HISTORICO, P.BUSQUEDA_EDITAR, P.ENTREGAR, P.ENTREGAR_EXPEDIENTE, P.ENTREGAR_DOCUMENTO, P.RECIBIR, P.RECIBIR_NUEVO, P.RECIBIR_REINGRESO, P.RECIBIR_CONFIRMAR, P.RECIBIR_MANUAL, P.PAGARE, P.PAGARE_BUSCAR, P.PAGARE_RECIBIR, P.PAGARE_ENTREGAR, P.LETRA_NUEVO, P.LETRA_ENTREGAR, P.LETRA_REINGRESO, P.LETRA_BUSCAR, P.IRONMOUNTAIN, P.IRONMOUNTAIN_SOLICITAR, P.IRONMOUNTAIN_RECIBIR, P.IRONMOUNTAIN_ARMAR, P.IRONMOUNTAIN_ENVIAR, P.IRONMOUNTAIN_ENTREGAR, P.IRONMOUNTAIN_CARGO, P.BOVEDA, P.BOVEDA_CAJA_RETIRAR, P.BOVEDA_CAJA_GUARDAR, P.BOVEDA_DOCUMENTO_RETIRAR, P.BOVEDA_DOCUMENTO_GUARDAR, P.IMPORTAR, P.IMPORTAR_ACTIVAS, P.IMPORTAR_PASIVAS, P.MANTENIMIENTO FROM ADMIN.USUARIO U LEFT JOIN ADMIN.PERMISO P ON U.ID_USUARIO = P.ID_USUARIO_FK WHERE U.NOMBRE_USUARIO = 'DJHONCON';
SELECT * FROM USUARIO;
select * from ldepartamento;
update ldepartamento set nombre_DEPARTAMENTO = 'OPNS' where id_departamento = 2;
SELECT * FROM USUARIO;
SELECT U.ID_USUARIO, U.NOMBRE_USUARIO, A.ID_AREA, A.NOMBRE_AREA FROM ADMIN.USUARIO U LEFT JOIN ADMIN.AREA A ON U.ID_AREA_FK = A.ID_AREA WHERE ANULADO = 0 AND A.REAL = 1 ORDER BY A.ORDEN, U.ORDEN;
select * from area;
select * from INVENTARIO_GENERAL;
select * from INVENTARIO_HISTORICO;
TRUNCATE TABLE INVENTARIO_GENERAL;
SELECT ID_INVENTARIO_GENERAL AS ID, TRIM(NUMERO_DE_CAJA) AS CAJA, TRIM(DEP.NOMBRE_DEPARTAMENTO) AS DEPART, TRIM(DOC.NOMBRE_DOCUMENTO) AS DOC, 
                        TO_CHAR(FECHA_DESDE, 'DD/MM/YYYY') AS DESDE, TO_CHAR(FECHA_HASTA, 'DD/MM/YYYY') AS HASTA, TRIM(DESCRIPCION_1) AS DESC_1, TRIM(DESCRIPCION_2) AS DESC_2,
                        TRIM(DESCRIPCION_3) AS DESC_3, TRIM(DESCRIPCION_4) AS DESC_4, TRIM(DESCRIPCION_5) AS DESC_5, TRIM(LE.NOMBRE_ESTADO) AS CUSTODIADO, TRIM(U.NOMBRE_USUARIO) AS POSEE, TO_CHAR(FECHA_POSEE, 'DD/MM/YYYY 24HH:MI:SS') AS FECHA
                        FROM (((ADMIN.INVENTARIO_GENERAL IG
                        LEFT JOIN ADMIN.LDEPARTAMENTO DEP ON IG.ID_DEPARTAMENTO_FK = DEP.ID_DEPARTAMENTO)
                        LEFT JOIN ADMIN.LDOCUMENTO DOC ON IG.ID_DOCUMENTO_FK = DOC.ID_DOCUMENTO)
                        LEFT JOIN ADMIN.USUARIO U ON U.ID_USUARIO = IG.ID_USUARIO_POSEE)
                        LEFT JOIN ADMIN.LESTADO LE ON LE.ID_ESTADO = IG.ID_ESTADO_FK;
                        SELECT NOMBRE_DESCRIPCION1 FROM ADMIN.LDESCRIPCION1 ORDER BY ORDEN ASC;
                        SELECT * FROM ADMIN.INVENTARIO_GENERAL;

select * from INVENTARIO_ANTERIOR;
select * from pagare_historico;
SELECT COUNT(*) FROM ADMIN.INVENTARIO_GENERAL WHERE DESC_CONCAT LIKE '%NEGOCIO;EXP;;;EXPEDIENTES DE CREDITO;1999-01-01012;0013333-PCO-D;HHHHHHHH;;%';
SELECT COUNT(*) FROM ADMIN.INVENTARIO_GENERAL WHERE DESC_CONCAT LIKE '%%';
UPDATE ADMIN.INVENTARIO_GENERAL SET NUMERO_DE_CAJA = '7004539', CAJA_CLIENTE = '7004539', ID_DEPARTAMENTO_FK = 3, ID_DOCUMENTO_FK = 7, DESCRIPCION_1 = 'PAGARES CANCELADOS', DESCRIPCION_2 = 'PAGARE 52659', DESCRIPCION_3 = 'TEMPALAY', DESCRIPCION_4 = 'BVNDIT LLLLLDS', DESCRIPCION_5 = '', NULL, NULL, FECHA_MODIFICA = TO_DATE('2022-10-07 11:11:38', 'YYYY-MM-DD HH:MI:SS'), ID_USUARIO_MODIFICA = 44, EXPEDIENTE = 0, DESC_CONCAT = 'PAGARES CANCELADOS;PAGARE 52659;TEMPALAY;BVNDIT LLLLLDS;;;;' WHERE ID_INVENTARIO_GENERAL = 13;
;
DECLARE
idnum number;
BEGIN
SELECT COUNT(*) INTO idnum FROM ADMIN.INVENTARIO_HISTORICO WHERE RECIBIDO = 0 AND ANULADO = 0;
DBMS_OUTPUT.PUT_LINE(idnum); 
end;

SELECT * FROM ADMIN.INVENTARIO_GENERAL;
