GRANT CREATE SESSION TO USERCHECK;
GRANT SELECT ON ADMIN.USUARIO TO USERCHECK;
GRANT UPDATE(JWT) ON ADMIN.USUARIO TO USERCHECK;
GRANT SELECT ON ADMIN.PERMISO TO USERCHECK;

GRANT CREATE SESSION TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.CENTRO_COSTO TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.INVENTARIO_ANTERIOR TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.INVENTARIO_GENERAL TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.INVENTARIO_HISTORICO TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.LAREA TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.LCLASIFICACION TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.LDEPARTAMENTO TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.LDETALLE TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.LDOCUMENTO TO CUSTODIAADM;
GRANT SELECT ON ADMIN.LESTADO TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.LPENDIENTE TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.LPRODUCTO TO CUSTODIAADM;
GRANT SELECT, UPDATE ON ADMIN.PERMISO TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT, DELETE ON ADMIN.TMP_CARRITO TO CUSTODIAADM;
GRANT SELECT ON ADMIN.UBICACION TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.USUARIO TO CUSTODIAADM;
GRANT SELECT, UPDATE, INSERT ON ADMIN.USUARIO_EXTERNO TO CUSTODIAADM;

INSERT INTO PERMISO (ID_USUARIO_FK) VALUES (121);
INSERT INTO PERMISO (ID_USUARIO_FK, BUSQUEDA, BUSQUEDA_HISTORICO, BUSQUEDA_EDITAR, MOVER, MOVER_EXPEDIENTE, MOVER_DOCUMENTO, VALIJA, VALIJA_NUEVO, VALIJA_VALIJA, VALIJA_TRANSICION, PAGARE, PAGARE_BUSCAR, PAGARE_RECIBIR, PAGARE_ENTREGAR, LETRA, LETRA_NUEVO, LETRA_ENTREGAR, LETRA_REINGRESO, LETRA_BUSCAR, MANTENIMIENTO)
VALUES (121, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0);


GRANT CREATE SESSION TO CUSTODIA1;
GRANT SELECT ON ADMIN.USUARIO TO CUSTODIA1;
GRANT SELECT ON ADMIN.PERMISO TO CUSTODIA1;
GRANT UPDATE(CAMBIAR_PASSWORD) ON ADMIN.USUARIO TO CUSTODIA1;
GRANT UPDATE(ULTIMA_ACTIVIDAD) ON ADMIN.USUARIO TO CUSTODIA1;
GRANT UPDATE(JWT) ON ADMIN.USUARIO TO CUSTODIA1;
GRANT UPDATE(PASSWORDHASH) ON ADMIN.USUARIO TO CUSTODIA1;
GRANT UPDATE(PASSWORDSALT) ON ADMIN.USUARIO TO CUSTODIA1;
GRANT UPDATE(EMAIL) ON ADMIN.USUARIO TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.INVENTARIO_GENERAL TO CUSTODIA1;
GRANT SELECT ON ADMIN.LDEPARTAMENTO TO CUSTODIA1;
GRANT SELECT ON ADMIN.LDOCUMENTO TO CUSTODIA1;
GRANT SELECT ON ADMIN.LESTADO TO CUSTODIA1;
GRANT SELECT, INSERT ON ADMIN.INVENTARIO_ANTERIOR TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.INVENTARIO_HISTORICO TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT, DELETE ON ADMIN.TMP_CARRITO TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.PAGARE TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.PAGARE_HISTORICO TO CUSTODIA1;
GRANT SELECT ON ADMIN.LPENDIENTE TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.USUARIO_EXTERNO TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.UBICACION TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.USUARIO_EXTERNO TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.USUARIO_EXTERNO TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.USUARIO_EXTERNO TO CUSTODIA1;
GRANT SELECT, UPDATE, INSERT ON ADMIN.USUARIO_EXTERNO TO CUSTODIA1;

CREATE ROLES ROL_CUSTODIAADM;
GRANT CREATE SESSION TO ROL_CUSTODIAADM;


update usuario set connuser = 'SicaADM' where ID_USUARIO = 1;
update usuario set connuser = 'Custodia1' where ID_USUARIO = 61;
update usuario set connuser = 'Custodia2' where ID_USUARIO = 62;
update usuario set connuser = 'Custodia3' where ID_USUARIO = 63;
update usuario set connuser = 'Default1' where ID_USUARIO = 64;
update usuario set connuser = 'Default2' where ID_USUARIO = 65;

select * from USUARIO;
select * from INVENTARIO_GENERAL;
select * from INVENTARIO_HISTORICO;
select * from ARMAR_CAJA_HISTORICO;
select * from permiso;
update permiso set nivel = 1 where id_usuario_fk = 1;
delete permiso where id_usuario_fk = 3;
delete permiso where id_usuario_fk = 44;
delete usuario where id_usuario = 3;
delete usuario where id_usuario = 44;
truncate table inventario_general;
truncate table INVENTARIO_ANTERIOR;
truncate table INVENTARIO_historico;
truncate table Pagare;
truncate table Pagare_Historico;
select * from Area;

update usuario set cambiar_password = 1 where id_usuario = 61;
update usuario set nombre_usuario = 'RIESGO1' where id_usuario = 64;
update permiso set pagare_recibir = 0, pagare_entregar = 0 where id_usuario_fk = 65;

--123456
INSERT INTO USUARIO (NOMBRE_USUARIO, CAMBIAR_PASSWORD, ACCESO_PERMITIDO, CERRAR_SESION, JWT, PASSWORDHASH, PASSWORDSALT, CONNUSER)
VALUES ('CUSTODIA18', 1, 1, 0, '', 'I0SaPl365354OGa9xCvLA3UMLksE7807vrcmSEc2QBMZtZA513cLzQ8cKCjaRHCDdHaKWr7fAdD5Pk0u3qig7Q==', 'Zfy6VyoRwvydGmeoVzTwpN6NcIQuhi9Mp4Oqqr9Pl82BlnIikuYa8xrijWFSMAQGYrrwo/j3i9ozyW6XMCFdWg==', 'Custodia1');

--TeCustodio
update usuario set PASSWORDSALT = 'wz2guOnOyn/+kYFoCRBpFWjpmUuvpaCETA21kJV7FCw304aVkJVKP/O4LedOm5yNRYTZ3AQM7N1hYz6kgcHfN7t6uoK0rXGJvxrTapekRUFJejAP/S5MDg2uHsRk7FwMaYJNBpuGjh3ir2Z6WidXAgSYhhPRf0a+czvmmYWX1m8=',
PASSWORDHASH = '5yEMbaAHkEVwE/0IticP7AKm26cTZOvIs0irynCjmqG4o26WuyRKha+KyNgscPRpS/TTXvZpJgihAxV239I1uw==' where ID_USUARIO = 103;
--123456
update usuario set PASSWORDSALT = 'kgAiuLF3+74EYc234M+iF/0Mv0FIfScsqrRim2RD4RbkDP0XIJPb+iG1/jOCoWnREz4CZ1X9KAlPHuIrnQlY+AXFHFNbGIQQ7X0s8KkXkL4OiAERWWiOIKQB7uv7abbuP74SCVC2nu51Ln+koi+bAJjehuYT06gd/RGILpb2dbM=',
PASSWORDHASH = 'I0SaPl365354OGa9xCvLA3UMLksE7807vrcmSEc2QBMZtZA513cLzQ8cKCjaRHCDdHaKWr7fAdD5Pk0u3qig7Q==' where ID_USUARIO = 121;

INSERT INTO PERMISO (ID_USUARIO_FK, BUSQUEDA, BUSQUEDA_HISTORICO, BUSQUEDA_EDITAR, ENTREGAR, ENTREGAR_EXPEDIENTE, ENTREGAR_DOCUMENTO, RECIBIR, RECIBIR_NUEVO, RECIBIR_REINGRESO, RECIBIR_CONFIRMAR, RECIBIR_MANUAL, PAGARE, PAGARE_BUSCAR, PAGARE_RECIBIR, PAGARE_ENTREGAR, LETRA, LETRA_NUEVO, LETRA_ENTREGAR, LETRA_REINGRESO, LETRA_BUSCAR, IRONMOUNTAIN, IRONMOUNTAIN_SOLICITAR, IRONMOUNTAIN_RECIBIR, IRONMOUNTAIN_ARMAR, IRONMOUNTAIN_ENVIAR, IRONMOUNTAIN_ENTREGAR, IRONMOUNTAIN_CARGO, BOVEDA, BOVEDA_CAJA_RETIRAR, BOVEDA_CAJA_GUARDAR, BOVEDA_DOCUMENTO_RETIRAR, BOVEDA_DOCUMENTO_GUARDAR, MANTENIMIENTO, IMPORTAR, IMPORTAR_ACTIVAS, IMPORTAR_PASIVAS, NIVEL)
VALUES (65, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3);
update usuario set orden = 10 where id_usuario = 62;
INSERT INTO PERMISO (ID_USUARIO_FK, BUSQUEDA, BUSQUEDA_HISTORICO, BUSQUEDA_EDITAR, ENTREGAR, ENTREGAR_EXPEDIENTE, ENTREGAR_DOCUMENTO, RECIBIR, RECIBIR_NUEVO, RECIBIR_REINGRESO, RECIBIR_CONFIRMAR, RECIBIR_MANUAL, PAGARE, PAGARE_BUSCAR, PAGARE_RECIBIR, PAGARE_ENTREGAR, LETRA, LETRA_NUEVO, LETRA_ENTREGAR, LETRA_REINGRESO, LETRA_BUSCAR, IRONMOUNTAIN, IRONMOUNTAIN_SOLICITAR, IRONMOUNTAIN_RECIBIR, IRONMOUNTAIN_ARMAR, IRONMOUNTAIN_ENVIAR, IRONMOUNTAIN_ENTREGAR, IRONMOUNTAIN_CARGO, BOVEDA, BOVEDA_CAJA_RETIRAR, BOVEDA_CAJA_GUARDAR, BOVEDA_DOCUMENTO_RETIRAR, BOVEDA_DOCUMENTO_GUARDAR, MANTENIMIENTO, IMPORTAR, IMPORTAR_ACTIVAS, IMPORTAR_PASIVAS, NIVEL)
VALUES (63, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2);

grant CREATE SESSION TO CAJERO;

REVOKE select, update, insert, delete ON INVENTARIO_GENERAL FROM USERCHECK;